---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : fimero
production_url : http://fimero.ruhoh.com

posts:
  permalink: /:categories/:title/
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'
